audiotoggle: Retry xdotool

diff --git a/bin/audiotoggle b/bin/audiotoggle
--- a/bin/audiotoggle
+++ b/bin/audiotoggle
@@ -2,7 +2,21 @@
 
 # Decide what to do when told to toggle play state
 
-win=$(xdotool getactivewindow getwindowname)
+: "${RETRIES:=5}"
+
+# TODO: work out why sometimes binding to KeyRelease isn't enough to guarantee
+# the keyboard is released...
+
+if ! win=$(xdotool getactivewindow getwindowname) && (( RETRIES )); then
+    (( RETRIES-- ))
+    sleep 0.1
+fi
+
+if ! (( RETRIES )); then
+    # We ran out of retries
+    printf '%s\n' "Ran out of xdotool retries" >&2
+    exit 5
+fi
 
 case $win in
     *YouTube*|*mpv*) xdotool key space ;;
