upload-photos: Always use s3cmd

diff --git a/bin/upload-photos b/bin/upload-photos
--- a/bin/upload-photos
+++ b/bin/upload-photos
@@ -16,15 +16,10 @@ extra_args=''
 # megabytes. In these cases, it makes sense to disable parallel upload.
 (( NO_PARALLEL )) || extra_args+=' -m'
 
-if (( FORCE_S3CMD )); then
-    # gsutil is b0rked, fall back to s3cmd
-    tmux new-session -d -s "$session_name" \
-        "while ! s3cmd sync -r . 's3://chrisdown-photos/$escaped_photo_dir/'; do sleep 20; done; echo Done; read"
-else
-    tmux new-session -d -s "$session_name" \
-        "while ! gsutil $extra_args rsync -r . 's3://chrisdown-photos/$escaped_photo_dir/'; do sleep 20; done; echo Done; read"
-    tmux split-window -h -t "$session_name:1" \
-        "while ! gsutil $extra_args rsync -r . 'gs://chris-down-photos/chrisdown-photos/$escaped_photo_dir/'; do sleep 20; done; echo Done; read"
-fi
+# 2020-07: Currently gsutil fails to upload to S3
+tmux new-session -d -s "$session_name" \
+    "while ! s3cmd sync -r . 's3://chrisdown-photos/$escaped_photo_dir/'; do sleep 20; done; echo Done; read"
+tmux split-window -h -t "$session_name:1" \
+    "while ! gsutil $extra_args rsync -r . 'gs://chris-down-photos/chrisdown-photos/$escaped_photo_dir/'; do sleep 20; done; echo Done; read"
 
 tmux attach -t "$session_name"
